[package]
name = "dui"
version = "0.1.0"
authors = ["Haze <me@haze.sh>"]

[dependencies]
scoped-pool = "1"
discord = { git = "https://github.com/ArtemGr/discord-rs" }
serde_json = "1.0"
serde_derive = "1.0"
serde = "1.0"
evmap = "4.0.0"